/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author juald
 */
public class VistaSocio extends javax.swing.JPanel {

    /**
     * Creates new form VistaSocio
     */
    public VistaSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUpdateSocio = new javax.swing.JButton();
        jLabelGestionDeMonitores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSocio = new javax.swing.JTable();
        jButtonAddSocio = new javax.swing.JButton();
        jButtonDeleteSocio = new javax.swing.JButton();

        jButtonUpdateSocio.setText("Actualización de Socio");
        jButtonUpdateSocio.setActionCommand("ActualizacionSocio");

        jLabelGestionDeMonitores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelGestionDeMonitores.setText("Gestión de Socios");

        TablaSocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaSocio);

        jButtonAddSocio.setText("Nuevo Socio");
        jButtonAddSocio.setActionCommand("NuevoSocio");

        jButtonDeleteSocio.setText("Baja de Socio");
        jButtonDeleteSocio.setActionCommand("BajaSocio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGestionDeMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateSocio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelGestionDeMonitores)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSocio)
                    .addComponent(jButtonDeleteSocio)
                    .addComponent(jButtonUpdateSocio))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaSocio;
    public javax.swing.JButton jButtonAddSocio;
    public javax.swing.JButton jButtonDeleteSocio;
    public javax.swing.JButton jButtonUpdateSocio;
    public javax.swing.JLabel jLabelGestionDeMonitores;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
